sonar.projectKey=Mcc-Mak_cicd-pipeline
sonar.organization=mcc-mak
sonar.host.url=https://sonarcloud.io

# Source configuration
sonar.sources=src
sonar.sourceEncoding=UTF-8

# Exclude testing suites and configuration frameworks from the vulnerability analyzer
sonar.exclusions=node_modules/**, dist/**, vite.config.ts, vite.config.js, **/*.test.ts, **/*.test.tsx, **/*.test.js

# Optional: Path to front-end coverage indicators if you use Vitest or Jest later
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
